[package]
name = "frontend"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
app = { path = "../app", default-features = false }
leptos = { workspace = true }

console_error_panic_hook.workspace = true
wasm-bindgen.workspace = true

[features]
default = []
hydrate = ["leptos/hydrate", "app/hydrate"]
